# -*- coding: utf-8 -*-
"""DIP - Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qSePqENK1e7j96epR9ZJhP-h2ilBzOgW
"""

import os
import cv2
import numpy as np
import shutil
import random
import matplotlib.pyplot as plt

import kagglehub

path = kagglehub.dataset_download("ugorjiir/gun-detection")
print("Path to dataset files:", path)

# جستجوی خودکار برای پیدا کردن پوشه تصاویر
found_path = ""
for root, dirs, files in os.walk(path):
    if any(f.endswith('.jpg') for f in files):
        found_path = root
        break

if found_path:
    dataset_path = found_path
    print(f" مسیر درست پیدا شد: {dataset_path}")

    # خواندن تصویر تست
    try:
        files = [f for f in os.listdir(dataset_path) if f.endswith('.jpg')]
        sample_img_path = os.path.join(dataset_path, files[0])
        img = cv2.imread(sample_img_path)

        if img is None:
            print(" ارور: فایل تصویر آسیب دیده یا خوانده نمی‌شود.")
        else:
            print(f" عکس با موفقیت بارگذاری شد. ابعاد: {img.shape}")
    except Exception as e:
        print(f" ارور در خواندن فایل: {e}")
else:
    print(" هیچ فایل jpg در این مسیر پیدا نشد. لطفاً دیتاست را چک کنید.")

# خواندن اولین تصویر برای تست
try:
    files = [f for f in os.listdir(dataset_path) if f.endswith('.jpg')]
    sample_img_path = os.path.join(dataset_path, files[0])
    img = cv2.imread(sample_img_path)
except:
    img = None

def image_processing_pipeline(image):
    if image is None: return None

    # تغییر اندازه به 224
    res = cv2.resize(image, (224, 224))

    # بهبود کنتراست هوشمند (CLAHE)
    lab = cv2.cvtColor(res, cv2.COLOR_BGR2LAB)
    l, a, b = cv2.split(lab)
    clahe = cv2.createCLAHE(clipLimit=3.0, tileGridSize=(8,8))
    img_clahe = cv2.merge((clahe.apply(l), a, b))
    img_clahe = cv2.cvtColor(img_clahe, cv2.COLOR_LAB2BGR)

    # فیلتر Sharpening برای لبه‌ها
    kernel = np.array([[0, -1, 0], [-1, 5, -1], [0, -1, 0]])
    img_sharp = cv2.filter2D(img_clahe, -1, kernel)

    # افزودن نویز گوسی
    noise = np.random.normal(0, 2, img_sharp.shape)
    # محدود کردن بین 0 و 255
    img_final = np.clip(img_sharp.astype(np.float32) + noise, 0, 255).astype('uint8')

    return res, img_clahe, img_sharp, img_final

# اجرای پردازش و نمایش
if img is not None:
    res, contrast, sharp, final = image_processing_pipeline(img)
    titles = ['Original (224x224)', 'Contrast Enhanced', 'Sharpened Edges', 'Final Processed']
    imgs = [res, contrast, sharp, final]

    plt.figure(figsize=(16, 4))
    for i in range(4):
        plt.subplot(1, 4, i+1)
        plt.imshow(cv2.cvtColor(imgs[i], cv2.COLOR_BGR2RGB))
        plt.title(titles[i])
        plt.axis('off')
    plt.show()
else:
    print("خطا: تصویر برای پردازش پیدا نشد!")

input_path = found_path
output_path = "/content/weapon_data_v3"
os.makedirs(output_path, exist_ok=True)

def advanced_processing(img):
    # استانداردسازی به 224
    img = cv2.resize(img, (224, 224))

    # بهبود کنتراست هوشمند (CLAHE)
    lab = cv2.cvtColor(img, cv2.COLOR_BGR2LAB)
    l, a, b = cv2.split(lab)
    clahe = cv2.createCLAHE(clipLimit=3.0, tileGridSize=(8,8))
    img = cv2.merge((clahe.apply(l), a, b))
    img = cv2.cvtColor(img, cv2.COLOR_LAB2BGR)

    # فیلتر Sharpening برای لبه‌ها
    kernel = np.array([[0, -1, 0], [-1, 5, -1], [0, -1, 0]])
    img = cv2.filter2D(img, -1, kernel)

    # افزودن نویز گوسی ملایم
    noise = np.random.normal(0, 2, img.shape)
    img = np.clip(img.astype(np.float32) + noise, 0, 255).astype('uint8')

    return img

print("شروع تولید دیتاست ۵۶۸۷ تصویری با ابعاد ۲۲۴...")

final_count = 0
# مرکز برای تصویر 224
center = (112, 112)

for filename in os.listdir(input_path):
    if filename.endswith(".jpg"):
        img_path = os.path.join(input_path, filename)
        image = cv2.imread(img_path)
        if image is None: continue

        # تصویر اصلی پردازش شده
        base = advanced_processing(image)
        cv2.imwrite(os.path.join(output_path, f"base_{filename}"), base)

        # چرخش ۱۵ درجه (Rotation)
        M_rot = cv2.getRotationMatrix2D(center, 15, 1.0)
        rotated = cv2.warpAffine(base, M_rot, (224, 224))
        cv2.imwrite(os.path.join(output_path, f"rot_{filename}"), rotated)

        # معکوس کردن (Flip)
        flipped = cv2.flip(base, 1)
        cv2.imwrite(os.path.join(output_path, f"flip_{filename}"), flipped)

        # تغییر مقیاس/زوم (Scaling)
        M_zoom = cv2.getRotationMatrix2D(center, 0, 1.2) # 20% زوم
        zoomed = cv2.warpAffine(base, M_zoom, (224, 224))
        cv2.imwrite(os.path.join(output_path, f"zoom_{filename}"), zoomed)

        # کپی برچسب‌ها برای تمام ۴ نسخه
        label_file = filename.replace('.jpg', '.txt')
        if os.path.exists(os.path.join(input_path, label_file)):
            with open(os.path.join(input_path, label_file), 'r') as f:
                content = f.read()
            for prefix in ['base_', 'rot_', 'flip_', 'zoom_']:
                with open(os.path.join(output_path, prefix + label_file), 'w') as f:
                    f.write(content)

        final_count += 4

print(f"عملیات تمام شد! تعداد تصاویر: {final_count}")

src_dir = '/content/weapon_data_v3'
base_output = '/content/final_weapon_dataset'

# ایجاد ساختار پوشه‌های استاندارد برای YOLO
for s in ['train', 'val', 'test']:
    os.makedirs(os.path.join(base_output, 'images', s), exist_ok=True)
    os.makedirs(os.path.join(base_output, 'labels', s), exist_ok=True)

# لیست کردن و مخلوط کردن تمام تصاویر برای آموزش عادلانه
all_images = [f for f in os.listdir(src_dir) if f.endswith('.jpg')]
random.shuffle(all_images)

total = len(all_images)
train_end = int(total * 0.7) # 70% آموزش
val_end = train_end + int(total * 0.2) # 20% اعتبار

print(f"در حال سازمان‌دهی {total} تصویر در ابعاد 224x224...")

for i, filename in enumerate(all_images):
    # تعیین پوشه مقصد بر اساس شاخص i
    if i < train_end: subset = 'train'
    elif i < val_end: subset = 'val'
    else: subset = 'test'

    # انتقال تصویر به پوشه مربوطه
    shutil.copy(os.path.join(src_dir, filename),
                os.path.join(base_output, 'images', subset, filename))

    # ۳. اصلاح و انتقال برچسب
    label_name = filename.replace('.jpg', '.txt')
    label_src = os.path.join(src_dir, label_name)

    if os.path.exists(label_src):
        with open(label_src, 'r') as f:
            lines = f.readlines()

        new_lines = []
        for line in lines:
            parts = line.split()
            # تغییر ID از دیتاست اصلی به IDهای استاندارد ما
            if parts[0] == '16': parts[0] = '0'   # Gun -> 0
            elif parts[0] == '15': parts[0] = '1' # Human -> 1
            new_lines.append(" ".join(parts) + "\n")

        # ذخیره فایل برچسب در پوشه استاندارد
        with open(os.path.join(base_output, 'labels', subset, label_name), 'w') as f:
            f.writelines(new_lines)

# تولید فایل data.yaml
yaml_content = f"""
train: {base_output}/images/train
val: {base_output}/images/val
test: {base_output}/images/test
nc: 2
names: ['Gun', 'Human']
"""
with open('/content/data.yaml', 'w') as f:
    f.write(yaml_content)

print(f" عملیات با موفقیت تمام شد! دیتای نهایی در {base_output} آماده است.")

yaml_content = f"""
train: /content/final_weapon_dataset/images/train
val: /content/final_weapon_dataset/images/val
test: /content/final_weapon_dataset/images/test

nc: 2 # تعداد کلاس‌ها (اسلحه و انسان)
names: ['Gun', 'Human'] # نام کلاس‌ها به ترتیب ID
"""

# ذخیره فایل در مسیر اصلی پروژه
with open('/content/data.yaml', 'w') as f:
    f.write(yaml_content.strip()) # استفاده از strip برای حذف فواصل خالی ابتدا و انتها

print(" فایل data.yaml با موفقیت ساخته شد و با کلاس‌های اصلاح شده (0: Gun, 1: Human) هماهنگ است.")

!pip install ultralytics

from ultralytics import YOLO
import torch

# ۲. چک کردن اینکه آیا کارت گرافیک فعال شده یا نه
device = 0 if torch.cuda.is_available() else 'cpu'
print(f"آموزش روی این سخت‌افزار اجرا می‌شود: {device}")

# ۳. بارگذاری مدل Small
model = YOLO('yolov8s.pt')

# ۴. شروع آموزش بهینه شده
results = model.train(
    data='/content/data.yaml',
    epochs=100,           # تعداد دور (Epoch) طبق مقاله
    imgsz=224,            # افزایش ابعاد به 224 برای دقت بالاتر در تشخیص اسلحه
    batch=16,             # تعداد تصاویر همزمان
    device=device,        # استفاده اجباری از کارت گرافیک (GPU)
    name='weapon_model_v2',
    optimizer='AdamW',    # بهینه‌ساز قوی‌تر برای رسیدن به دقت ۹۸٪
    lr0=0.01              # نرخ یادگیری اولیه
)

# بارگذاری بهترین مدل ساخته شده (best.pt)
model_path = '/content/runs/detect/weapon_model_v2/weights/best.pt'
model = YOLO(model_path)

test_images_path = '/content/final_weapon_dataset/images/test'
test_images = [os.path.join(test_images_path, f) for f in os.listdir(test_images_path) if f.endswith('.jpg')]

samples = random.sample(test_images, 3)
plt.figure(figsize=(20, 10))

for i, img_path in enumerate(samples):
    # اجرای مدل روی عکس (با آستانه اطمینان 0.25)
    results = model.predict(source=img_path, imgsz=224, conf=0.25)

    res_plotted = results[0].plot()

    plt.subplot(1, 3, i+1)
    plt.imshow(cv2.cvtColor(res_plotted, cv2.COLOR_BGR2RGB))
    plt.title(f"Test Result {i+1}")
    plt.axis('off')

plt.show()

print("خروجی مدل")

import shutil
from google.colab import files

# زیپ کردن پوشه نتایج نهایی
folder_to_zip = '/content/runs/detect/weapon_model_v2'
output_filename = 'Weapon_Detection_Final_Results'

shutil.make_archive(output_filename, 'zip', folder_to_zip)

# دانلود فایل زیپ به کامپیوتر شما
files.download(f'{output_filename}.zip')

print(" فایل نتایج (شامل نمودارها و مدل) در حال دانلود است...")